all_channels = ["123prizes", "4x4bux_com", "abitback", "anythingfree4you", "ayuwage", "bearby", "beerpongmoney", "bitcoinget", "bofferz", "brightspyre", "browse4bux", "btcworker", "buxense", "callmemoney", "cashclam", "cashcrate", "cashole", "cf_internal", "cfofferwall", "clickfair", "clicksfx", "clixearn", "clixplanet", "clixsense", "clixted", "coinworker", "cotter", "crowdguru", "dailysurveypanel", "datapurify", "dealbarbiepays", "diamondtask", "dollarrewardz", "dollarsgpt", "dollarsignup", "dreamgpt", "earngpt", "earnthemost", "easycashclicks", "easytasks", "embee", "epicrewardz", "errtopc", "eup_slw", "extralunchmoney", "fairbux", "fastcashgpt", "fastdollarz", "fastestrewards", "fepcrowdflower", "freeride", "fsprizes", "fusioncash", "fusioncashsafe", "getpaid", "getpaidto", "giftcardgpt", "giftgpt", "gifthulk", "gifthunterclub", "globalactioncash", "golddiggergpt", "goldtasks", "gpstar", "gptbanks", "gptbucks", "gptclicks", "gptdollars", "gptfly", "gptking", "gptpal", "honey_dollarz", "ibuxers", "imerit_india", "inboxpounds", "incentivespay", "inobux", "instagc", "instantbucks", "instantrewardz", "irazoo", "irewardme", "jammp", "keeprewarding", "luckykoin", "luckytaskz", "magicgptchannel", "makethatdollar", "matomy", "mbc", "memolink", "meprizescf", "mob", "motoclixx", "mycashtasks", "myrightbux", "neodev", "newrewardsgallore", "newtoncircus_test", "northclicks", "offernation", "onestopgpt", "paiddailysurveys", "pandasbux", "panelrewards", "peoplesgpt", "pforads", "piggybankgpt", "piyanstantrewards", "piyoogle", "plusdollars", "pocketmoneygpt", "point_dollars", "points2shop", "points4rewards", "pokerowned", "prizeplank", "prizerebel", "prizesgalore", "prizezombie", "probux", "prodege", "proudclick", "ptc123", "ptchits4u", "ptctime", "qpr", "quickrewards", "racegpt", "razegpt", "rewardingways", "rewardit_test", "rewardok", "rewards1", "rewardsspot", "sendearnings", "sensebux", "sharecashgpt", "simplegpt", "snowcirrustechbpo", "stuffpoint", "superpayme", "supersonicads", "surewardsgpt", "surveyhunt", "surveymad", "surveytokens", "surveywage", "taskbastion", "taskpayers", "tasks", "tasks4dollars", "taskspay", "thespartaninstitute", "tikitreasure", "treasuretrooper", "tremorgames", "uniquerewards", "vdsolutions", "vivatic", "workersgpt", "wrkshop", "yovia", "zephyrclix", "zoombucks", "zorbor"]

v1_channels = ["bizooki", "casualcollective", "hotfile", "innopoints", "ip2010", "irdesign", "mp2010", "pr2010", "sedgroup", "sponsorpay", "trg", "iphone", "sometrics", "trial_pay"]

bad_channels = ["amt","brightspyre","coinworker","matomy", "test", "probux", "clixplanet", "point_dollars"]

channels = all_channels - v1_channels - bad_channels

qchannels = channels.map {|c| "channels%5B%5D=#{c}" }.join("&")

api_order_command = "curl -X POST 'https://api.crowdflower.com/v1/jobs/#{new_job_id}/orders.json?key=#{API_KEY}&#{qchannels}&debit%5Bunits_count%5D=#{units_to_order}'"